#environment: development
server:
  port: 8044
  servlet:
    context-path: /sshop

spring:
  application:
    name: SSHOP_backend
  datasource:
    url: jdbc:postgresql://localhost:5433/sshop
    username: postgres
    password: 123456
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update #Hibernate ddl auto options: update, create, drop, create-drop, validate, none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        # dialect: org.hibernate.dialect.PostgreSQLDialect
        # jdbc.lob.non_contextual_creation: true #doestn't use sessions to persist effectively
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

logging:
  level:
    org.springframework.security: DEBUG

media:
  uri: "file:///D:/.Project/kltn/SSHOP_media"

jwt:
  access:
    secret-key: "<string>" #base64 64 bytes
    valid-duration: 1 #days
  refresh:
    secret-key: "<string>" #hex 64 bytes
    valid-duration: 7 #days

oauth2:
  google:
    client-id: "<string>"
    client-secret: "<string>"
    redirect-uri: "http://localhost:3066/authenticate"
    grant-type: "authorization_code"

